apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/hybrit-jenkins/configuration-admin-service:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/hybrit-jenkins/configuration-admin-service:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: configuration-admin-service
        chartPath: charts/configuration-admin-service
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/hybrit-jenkins/configuration-admin-service"
          image.tag: "{{.TAG}}"
